///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginModelUserDetail {
/*
{
  "id": "2128",
  "name": "Kashif Ali",
  "profile_image": "https://rmsportal.net/assets/uploads/avatar-round-1-1024x1024.png",
  "email_address": "mkashifali541@gmail.com",
  "suspended": "0",
  "from_site": "0",
  "approved": "2",
  "added_by_title": "gtr"
} 
*/

  String? id;
  String? name;
  String? profileImage;
  String? emailAddress;
  String? suspended;
  String? fromSite;
  String? approved;
  String? addedByTitle;

  LoginModelUserDetail({
    this.id,
    this.name,
    this.profileImage,
    this.emailAddress,
    this.suspended,
    this.fromSite,
    this.approved,
    this.addedByTitle,
  });
  LoginModelUserDetail.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    name = json['name']?.toString();
    profileImage = json['profile_image']?.toString();
    emailAddress = json['email_address']?.toString();
    suspended = json['suspended']?.toString();
    fromSite = json['from_site']?.toString();
    approved = json['approved']?.toString();
    addedByTitle = json['added_by_title']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['profile_image'] = profileImage;
    data['email_address'] = emailAddress;
    data['suspended'] = suspended;
    data['from_site'] = fromSite;
    data['approved'] = approved;
    data['added_by_title'] = addedByTitle;
    return data;
  }
}

class LoginModel {
/*
{
  "code": 203,
  "status": "OK",
  "message": "vendor",
  "user_detail": {
    "id": "2128",
    "name": "Kashif Ali",
    "profile_image": "https://rmsportal.net/assets/uploads/avatar-round-1-1024x1024.png",
    "email_address": "mkashifali541@gmail.com",
    "suspended": "0",
    "from_site": "0",
    "approved": "2",
    "added_by_title": "gtr"
  }
} 
*/

  int? code;
  String? status;
  String? message;
  LoginModelUserDetail? userDetail;

  LoginModel({
    this.code,
    this.status,
    this.message,
    this.userDetail,
  });
  LoginModel.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toInt();
    status = json['status']?.toString();
    message = json['message']?.toString();
    userDetail = (json['user_detail'] != null)
        ? LoginModelUserDetail.fromJson(json['user_detail'])
        : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['status'] = status;
    data['message'] = message;
    if (userDetail != null) {
      data['user_detail'] = userDetail!.toJson();
    }
    return data;
  }
}
