///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class BidModelData {
/*
{
  "id": "1619",
  "detail_id": "1684",
  "project_name": "NIC Card Replacement 13 Oct France",
  "project_location": "Épagny-Metz-Tessy,  France",
  "booking_type": "Hourly - Without Travel",
  "consultant_detail": "RC<br>Kashif",
  "call_out_rate": "234234",
  "travel_expense": "No",
  "purchase_expense": "No",
  "payment_type": "All to my account",
  "technician_charges_percentage": "",
  "provider_charges_percentage": "",
  "description": " saq234q4wadfg23234 234"
} 
*/

  String? id;
  String? detailId;
  String? projectName;
  String? projectLocation;
  String? bookingType;
  String? consultantDetail;
  String? callOutRate;
  String? travelExpense;
  String? purchaseExpense;
  String? paymentType;
  String? technicianChargesPercentage;
  String? providerChargesPercentage;
  String? description;

  BidModelData({
    this.id,
    this.detailId,
    this.projectName,
    this.projectLocation,
    this.bookingType,
    this.consultantDetail,
    this.callOutRate,
    this.travelExpense,
    this.purchaseExpense,
    this.paymentType,
    this.technicianChargesPercentage,
    this.providerChargesPercentage,
    this.description,
  });
  BidModelData.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toString();
    detailId = json['detail_id']?.toString();
    projectName = json['project_name']?.toString();
    projectLocation = json['project_location']?.toString();
    bookingType = json['booking_type']?.toString();
    consultantDetail = json['consultant_detail']?.toString();
    callOutRate = json['call_out_rate']?.toString();
    travelExpense = json['travel_expense']?.toString();
    purchaseExpense = json['purchase_expense']?.toString();
    paymentType = json['payment_type']?.toString();
    technicianChargesPercentage =
        json['technician_charges_percentage']?.toString();
    providerChargesPercentage = json['provider_charges_percentage']?.toString();
    description = json['description']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['detail_id'] = detailId;
    data['project_name'] = projectName;
    data['project_location'] = projectLocation;
    data['booking_type'] = bookingType;
    data['consultant_detail'] = consultantDetail;
    data['call_out_rate'] = callOutRate;
    data['travel_expense'] = travelExpense;
    data['purchase_expense'] = purchaseExpense;
    data['payment_type'] = paymentType;
    data['technician_charges_percentage'] = technicianChargesPercentage;
    data['provider_charges_percentage'] = providerChargesPercentage;
    data['description'] = description;
    return data;
  }
}

class BidModel {
/*
{
  "code": 200,
  "status": "OK",
  "data": [
    {
      "id": "1619",
      "detail_id": "1684",
      "project_name": "NIC Card Replacement 13 Oct France",
      "project_location": "Épagny-Metz-Tessy,  France",
      "booking_type": "Hourly - Without Travel",
      "consultant_detail": "RC<br>Kashif",
      "call_out_rate": "234234",
      "travel_expense": "No",
      "purchase_expense": "No",
      "payment_type": "All to my account",
      "technician_charges_percentage": "",
      "provider_charges_percentage": "",
      "description": " saq234q4wadfg23234 234"
    }
  ]
} 
*/

  int? code;
  String? status;
  List<BidModelData?>? data;

  BidModel({
    this.code,
    this.status,
    this.data,
  });
  BidModel.fromJson(Map<String, dynamic> json) {
    code = json['code']?.toInt();
    status = json['status']?.toString();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <BidModelData>[];
      v.forEach((v) {
        arr0.add(BidModelData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['code'] = code;
    data['status'] = status;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
