// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'basic_info.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

BasicInfo _$BasicInfoFromJson(Map<String, dynamic> json) => BasicInfo(
      id: json['id'] as String?,
      firstName: json['first_name'] as String?,
      middleName: json['middle_name'] as String?,
      lastName: json['last_name'] as String?,
      registrationDate: json['registration_date'] as String?,
      dob: json['dob'] as String?,
      nationalId: json['national_id'] as String?,
      houseNumber: json['house_number'] as String?,
      streetNumber: json['street_number'] as String?,
      city: json['city'] as String?,
      province: json['province'] as String?,
      postalCode: json['postal_code'] as String?,
      country: json['country'] as String?,
      lat: json['lat'] as String?,
      lng: json['lng'] as String?,
      contactNumberPrimary: json['contact_number_primary'] as String?,
      contactNumberSecondary: json['contact_number_secondary'] as String?,
      phoneNumberLandline: json['phone_number_landline'] as String?,
      whatsappContactNumber: json['whatsapp_contact_number'] as String?,
      emailAddress: json['email_address'] as String?,
      password: json['password'] as String?,
      skypeid: json['skypeid'] as String?,
      workingExperienceMonth: json['working_experience_month'] as String?,
      workingExperienceYear: json['working_experience_year'] as String?,
      currentLocationCountry: json['current_location_country'] as String?,
      interestedIn: json['interested_in'] as String?,
      availability: json['availability'] as String?,
      availabilityTimeInBracket:
          json['availability_time_in_bracket'] as String?,
      noticeTimeForFullDay: json['notice_time_for_full_day'] as String?,
      mobilityRegionLocation: json['mobility_region_location'] as String?,
      employmentStatus: json['employment_status'] as String?,
      paymentMechanism: json['payment_mechanism'] as String?,
      consultantHiredFrom: json['consultant_hired_from'] as String?,
      positionAgainst: json['position_against'] as String?,
      otherPosition: json['other_position'] as String?,
      coverageId: json['coverage_id'] as String?,
      requestId: json['request_id'] as String?,
      sdcCityCountryId: json['sdc_city_country_id'] as String?,
      profileImage: json['profile_image'] as String?,
      formPercentage: json['form_percentage'] as String?,
      vendorTypeId: json['vendor_type_id'] as String?,
      vendorId: json['vendor_id'] as String?,
      companyId: json['company_id'] as String?,
      approved: json['approved'] as String?,
      addedBy: json['added_by'] as String?,
      addedByTitle: json['added_by_title'] as String?,
      gtrNotifRead: json['gtr_notif_read'] as String?,
      sdcAddedNotifToGtm: json['sdc_added_notif_to_gtm'] as String?,
      rejectedByGtr: json['rejected_by_gtr'] as String?,
      reasonForRejectionGtr: json['reason_for_rejection_gtr'] as String?,
      rejectedByGtrNotif: json['rejected_by_gtr_notif'] as String?,
      acceptedByGtrNotif: json['accepted_by_gtr_notif'] as String?,
      assignedToUser: json['assigned_to_user'] as String?,
      assignedNotifRead: json['assigned_notif_read'] as String?,
      gtmRejectionComment: json['gtm_rejection_comment'] as String?,
      gtmApprovalNotifToGtr: json['gtm_approval_notif_to_gtr'] as String?,
      addedDate: json['added_date'] as String?,
      editedDate: json['edited_date'] as String?,
      link: json['link'] as String?,
      smsAlert: json['sms_alert'] as String?,
      opened: json['opened'] as String?,
      suspended: json['suspended'] as String?,
      fromSite: json['from_site'] as String?,
      siteRejectionByGtr: json['site_rejection_by_gtr'] as String?,
      gtmActivityNew: json['gtm_activity_new'] as String?,
      gtmActivitySent: json['gtm_activity_sent'] as String?,
      gtrActivitySeen: json['gtr_activity_seen'] as String?,
      phoneVerified: json['phone_verified'] as String?,
      verificationCode: json['verification_code'] as String?,
    );

Map<String, dynamic> _$BasicInfoToJson(BasicInfo instance) => <String, dynamic>{
      'id': instance.id,
      'first_name': instance.firstName,
      'middle_name': instance.middleName,
      'last_name': instance.lastName,
      'registration_date': instance.registrationDate,
      'dob': instance.dob,
      'national_id': instance.nationalId,
      'house_number': instance.houseNumber,
      'street_number': instance.streetNumber,
      'city': instance.city,
      'province': instance.province,
      'postal_code': instance.postalCode,
      'country': instance.country,
      'lat': instance.lat,
      'lng': instance.lng,
      'contact_number_primary': instance.contactNumberPrimary,
      'contact_number_secondary': instance.contactNumberSecondary,
      'phone_number_landline': instance.phoneNumberLandline,
      'whatsapp_contact_number': instance.whatsappContactNumber,
      'email_address': instance.emailAddress,
      'password': instance.password,
      'skypeid': instance.skypeid,
      'working_experience_month': instance.workingExperienceMonth,
      'working_experience_year': instance.workingExperienceYear,
      'current_location_country': instance.currentLocationCountry,
      'interested_in': instance.interestedIn,
      'availability': instance.availability,
      'availability_time_in_bracket': instance.availabilityTimeInBracket,
      'notice_time_for_full_day': instance.noticeTimeForFullDay,
      'mobility_region_location': instance.mobilityRegionLocation,
      'employment_status': instance.employmentStatus,
      'payment_mechanism': instance.paymentMechanism,
      'consultant_hired_from': instance.consultantHiredFrom,
      'position_against': instance.positionAgainst,
      'other_position': instance.otherPosition,
      'coverage_id': instance.coverageId,
      'request_id': instance.requestId,
      'sdc_city_country_id': instance.sdcCityCountryId,
      'profile_image': instance.profileImage,
      'form_percentage': instance.formPercentage,
      'vendor_type_id': instance.vendorTypeId,
      'vendor_id': instance.vendorId,
      'company_id': instance.companyId,
      'approved': instance.approved,
      'added_by': instance.addedBy,
      'added_by_title': instance.addedByTitle,
      'gtr_notif_read': instance.gtrNotifRead,
      'sdc_added_notif_to_gtm': instance.sdcAddedNotifToGtm,
      'rejected_by_gtr': instance.rejectedByGtr,
      'reason_for_rejection_gtr': instance.reasonForRejectionGtr,
      'rejected_by_gtr_notif': instance.rejectedByGtrNotif,
      'accepted_by_gtr_notif': instance.acceptedByGtrNotif,
      'assigned_to_user': instance.assignedToUser,
      'assigned_notif_read': instance.assignedNotifRead,
      'gtm_rejection_comment': instance.gtmRejectionComment,
      'gtm_approval_notif_to_gtr': instance.gtmApprovalNotifToGtr,
      'added_date': instance.addedDate,
      'edited_date': instance.editedDate,
      'link': instance.link,
      'sms_alert': instance.smsAlert,
      'opened': instance.opened,
      'suspended': instance.suspended,
      'from_site': instance.fromSite,
      'site_rejection_by_gtr': instance.siteRejectionByGtr,
      'gtm_activity_new': instance.gtmActivityNew,
      'gtm_activity_sent': instance.gtmActivitySent,
      'gtr_activity_seen': instance.gtrActivitySeen,
      'phone_verified': instance.phoneVerified,
      'verification_code': instance.verificationCode,
    };
